<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Darts Tournament');

echo $this->doctype(); ?>
<html lang="en">
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headLink()->prependStylesheet($this->baseUrl() . '/css/main.css'); ?>
</head>
<body>
<div id="content">
    <h1><?= $this->escape($this->title); ?></h1>
    <?= $this->layout()->content; ?>
</div>
</body>
</html>
